var data = [{
                			src:'../css/assets/slider/image1.png',
                			cont:'远眺',
                			text:'能和心爱的人一起睡觉，是件幸福的事情；可是，打呼噜怎么办？'
                		},{
                			src:'../css/assets/slider/image2.png',
                			cont:'木屋',
                			text:'想要这样一间小木屋，夏天挫冰吃瓜，冬天围炉取暖.'
                		},{
                			src:'../css/assets/slider/image3.png',
                			cont:'烤炉',
                			text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                		},{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                },{
                                        src:'../css/assets/slider/image3.png',
                                        cont:'烤炉',
                                        text:'烤炉模式的城，到黄昏，如同打翻的调色盘一般.'
                                }];			